#!/bin/bash
# vim: set ft=sh

set -e -x

export GOPATH=$PWD/Godeps/_workspace:$GOPATH

FIRST_GOPATH=`echo $GOPATH | cut -d':' -f1`

mkdir -p $FIRST_GOPATH/bin
export PATH=$FIRST_GOPATH/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -failOnPending -randomizeAllSpecs -race "$@"
