#!/bin/bash
# vim: set ft=sh

set -e -x

FIRST_GOPATH=`echo $GOPATH | cut -d':' -f1`

mkdir -p $FIRST_GOPATH/bin
export PATH=$FIRST_GOPATH/bin:$PATH

go get -t -v ./...

## Lock down etcd since latest code is very broken
## See: https://github.com/coreos/etcd/issues/986
mkdir -p $FIRST_GOPATH/src/github.com/coreos/etcd
pushd $FIRST_GOPATH/src/github.com/coreos/etcd
  git clone https://github.com/coreos/etcd.git . || true
  git checkout 0a2384bf4daec35a814244dc4d885e14f18b5ef1
  go install .
popd

go get github.com/dustin/goveralls
go get code.google.com/p/go.tools/cmd/cover
go install github.com/onsi/ginkgo/ginkgo

ginkgo -cover -v -r -failOnPending -randomizeAllSpecs -race

# don't leak coveralls token
set +x

if [ -n "$COVERALLS_TOKEN" ]; then
  profiles=$(find . -name '*.coverprofile' | grep -v fake | grep -v integration.coverprofile)

  echo mode: set > all.coverprofile
  cat $profiles | grep -v mode: >> all.coverprofile

  goveralls -service drone.io -coverprofile=all.coverprofile $COVERALLS_TOKEN || \
    echo "Coveralls failed. :("
fi
